# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_restaurantlocation_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantlocation',
            name='slug',
        ),
    ]
