# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_remove_restaurantlocation_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='slug',
            field=models.SlugField(default='teste', unique=True),
            preserve_default=False,
        ),
    ]
